name: cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  secdev-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Extract SecDev App Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/secdev-app

      - name: Build and Push SecDev App
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/secdev-app:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/secdev-app:latest
          labels: ${{ steps.meta.outputs.labels }}
